### ISSUE TITLE
Issues found in Spirits Page

### ISSUE THREAD

**Issue by Thanusha12** [hlxsites/sazerac-99brandparty#98]
1.The background used for this page is different from the live page
https://main--sazerac-99brandparty--hlxsites.hlx.live/spirits 

2.The title "99® BRAND SPIRITS COLLECTION" is on the left, while it is on the right in live site.
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/803c4a99-267d-4e45-82d7-e302a2f85c65)

3.Spelling correction - "99® RA SPBERRY VODKA" needs to be corrected to "99® RASPBERRY VODKA"
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/6721823f-106c-4416-a5ae-6cd07f5ccc22)

**Comment by RemoLiechti** [comment]
1. the backgrounds are the same for me, or am I looking at the wrong thing?
original site:
<img width="1411" alt="image" src="https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/c9152f0d-6c96-490e-a4f6-7b2f719c9923">

on our site:
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/ec43177e-d84e-47ae-9e8c-a3ada6f34bec)



2. I have done. this intentionally. When you switch to mobile view, the spirits collection text was somewhere in the middle and you had to scroll. Now, It's on top which seems to be a better user experience. Keep on left or move to right?
Also, we show two instead of one product in mobile view, to be consistent with all products and new products pages.

Original site:
<img width="379" alt="image" src="https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/ef583058-7e80-41e7-85f9-338f447ebbd1">
<img width="383" alt="image" src="https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/a1ae612e-f6a3-4b84-bbe9-ce200d4512b9">
<img width="385" alt="image" src="https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/c47f5dbf-7154-482a-a093-46354b0ab87c">

on our site:
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/64617f39-4e73-493f-9ed6-ae2f4e3bf3d0)
![image](https://github.com/hlxsites/sazerac-99brandparty/assets/141611642/7a5c1989-ad7d-477e-a6db-f0fa9e83ea1b)

3. fixed

**Comment by Thanusha12** [comment]
1. okay My screen size is smaller - I viewed it in 1920x1080 it looks good.
2. okay got your point.

**Comment by RemoLiechti** [comment]
ok great, so we can close this issue then?

**Comment by Thanusha12** [comment]
Yes sure.
