### ISSUE TITLE
"Next" button is missing 

### ISSUE THREAD

**Issue by Thanusha12** [hlxsites/sazerac-99brandparty#99]
1.The "Next" button is missing in the below page : 

 https://main--sazerac-99brandparty--hlxsites.hlx.live/products/99-xxpresso 

![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/645d3e71-920d-4258-b092-59b9f06a08ce)

Original site - 

![image](https://github.com/hlxsites/sazerac-99brandparty/assets/122380883/a4006958-662c-4bf2-a7e0-9a40b53cdc34)

**Comment by RemoLiechti** [comment]
Yes, this is due to the way the new way the navigation works. The data comes from the index, so now you can simply add new product documents and they will automatically be added to the navigation in the header, and the previous and next buttons will incorporate them. 
Therefore there is no next button on the last product in the list (the xxpresso). 
While on the original site, the next button on xxpresso simply linked to party packs. But from there you could not go with a next button to spirits either. As this was not consistent, I decided to simply keep it the way it is now.
If you believe we should add a next button to go to party packs, let me know, we can manually add this. However, I believe this is misleading the user.

**Comment by Thanusha12** [comment]
Yes I also felt it is inconsistent as we cannot navigate to the next spirit from the party packs

I think we can keep it the way it is now.

this ticket can be closed too.

**Comment by RemoLiechti** [comment]
agree, thanks.
